version: "3"

## 本番環境は docker-compose -f prod.yml up を実行
services:
  db:
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    tty: true
    stdin_open: true
    depends_on: 
      - db
      - chrome
    ports:
      - '3000:3000'
    volumes: 
      - .:/tan5
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
#volumes:
#  postgresql-data:
#    driver: local
    
