version: "3"
services:
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./tmp/sockets:/tan5/tmp/sockets
      - ./public:/tan5/public

  web:
    build: .
    #command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes: 
      - .:/tan5
      - ./public:/tan5/public
      - ./tmp:/tan5/tmp
      - ./log:/tan5/log
    
